name: pr

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

permissions:
  contents: write
  id-token: write
  pull-requests: read
  packages: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  detect-changes:
    uses: ./.github/workflows/detect-changes.yml

  build-and-commit:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.smart-switches == 'true' }}
    uses: ./.github/workflows/docker-build.yml
    with:
      rebuild-server: ${{ needs.detect-changes.outputs.bot-change != 'true' && needs.detect-changes.outputs.server == 'true' }}
      rebuild-site: ${{ needs.detect-changes.outputs.bot-change != 'true' && needs.detect-changes.outputs.site == 'true' }}
      push: false
    secrets: inherit

  preview-version-update:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.version-update == 'true' }}
    uses: ./.github/workflows/version-update.yml
    with:
      dry-run: true
    secrets: inherit

  pr-ready:
    needs:
      - detect-changes
      - build-and-commit
      - preview-version-update
    runs-on: ubuntu-latest
    if: always()
    steps:
      -
        name: Validate jobs
        if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
          exit 1
      -
        name: Fail if changes generated
        if: ${{ needs.build-and-commit.outputs.pushed-changes == 'true' }}
        run: |
          echo "::error title=${{ github.workflow }}::changes pushed, not ready"
          exit 1
